# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := Animus glfw imgui stb

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

Animus: glfw stb imgui
	@echo "==== Building Animus ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Animus.make

glfw: 
	@echo "==== Building glfw ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f glfw.make

imgui: 
	@echo "==== Building imgui ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f imgui.make

stb: 
	@echo "==== Building stb ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f stb.make

clean:
	@${MAKE} --no-print-directory -C . -f Animus.make clean
	@${MAKE} --no-print-directory -C . -f glfw.make clean
	@${MAKE} --no-print-directory -C . -f imgui.make clean
	@${MAKE} --no-print-directory -C . -f stb.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Animus"
	@echo "   glfw"
	@echo "   imgui"
	@echo "   stb"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
